/* Deterministic static regression checks for AP-01..31 technical fixes. */
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=__dirname;
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const walk=d=>fs.readdirSync(d,{withFileTypes:true}).flatMap(e=>e.name==='.git'||e.name==='assets'?[]:e.isDirectory()?walk(path.join(d,e.name)):[path.join(d,e.name)]);
const htmlFiles=walk(root).filter(p=>p.endsWith('.html'));
const html=htmlFiles.map(p=>({p,body:fs.readFileSync(p,'utf8')}));
const js=read('assets/js/main.js'),css=read('assets/css/styles.css');
const preview=html.filter(x=>x.p.endsWith(path.join('index.html'))&&x.body.includes('/adaptprint-static-preview/'));
const menus=preview;
assert.strictEqual(preview.length,13,'exactly 13 preview pages must be identified');
preview.forEach(x=>assert(/<meta name="robots" content="noindex,follow">/.test(x.body),`preview robots missing: ${x.p}`));
menus.forEach(x=>assert(!/tel:\+302(?!112181704)/.test(x.body),`incorrect menu phone href: ${x.p}`));
assert(/const MOBILE_BREAKPOINT=1024/.test(js),'JS mobile breakpoint must be 1024');
assert(/@media\(max-width:1023px\)/.test(css)&&/@media\(min-width:1024px\)/.test(css),'CSS mobile breakpoint must be 1024');
assert(/backdrop\.hidden=true/.test(js)&&/backdrop\.inert=true/.test(js),'closed backdrop must be hidden and inert');
assert(/aria-pressed/.test(js)&&/filterCount/.test(js),'portfolio filters need pressed state and live count');
assert(/function trapFocus/.test(js)&&/lastFocus\?\.focus/.test(js),'lightbox focus trap/restoration missing');
assert(/isValidContact/.test(js)&&/isValidUrl/.test(js)&&/πρόγραμμα email/.test(js),'form validation/handoff UX missing');
assert(/calcWidth/.test(js)&&/orientation/.test(js)&&/margin/.test(js),'DTF calculation metadata missing');
assert.strictEqual((js.match(/getElementById\('sendCalc'\)\?\.addEventListener/g)||[]).length,1,'DTF quote action must have one insertion handler');
html.forEach(x=>assert(!x.body.includes('[ΝΑ ΕΠΙΒΕΒΑΙΩΘΕΙ'),'public editorial marker remains: '+x.p));
const dtf=html.find(x=>x.p.endsWith(path.join('stampes-dtf-me-to-metro','index.html'))).body;
assert(/step="0\.1"/.test(dtf)&&/aria-live="polite"/.test(dtf),'DTF decimal input/accessibility missing');
assert(/name="service_context"/.test(dtf)&&/name="project_context"/.test(dtf),'quote context fields missing');
const contact=html.find(x=>x.p.endsWith(path.join('contact-us','index.html'))).body;
assert(/href="tel:\+302112181704"/.test(contact),'main contact mobile tel link missing');
assert(/<iframe\b[^>]*src="https:\/\/www\.google\.com\/maps/.test(contact)&&/loading="eager"/.test(contact),'map must load immediately on the contact page');
assert(!/map-load|data-map-src/.test(contact),'obsolete deferred-map controls must be removed');
preview.forEach(x=>assert(/"latitude": ?37\.9561061, ?"longitude": ?23\.6406674/.test(x.body),`AP-21 coordinates missing: ${x.p}`));
const facebook='https://www.facebook.com/profile.php?id=100091100274168&mibextid=wwXIfr&rdid=kkdWRaJcPuOdVVBY&share_url=https%3A%2F%2Fwww.facebook.com%2Fshare%2F196ubr4Kzg%2F%3Fmibextid%3DwwXIfr#';
html.forEach(x=>{if(x.body.includes('facebook'))assert(x.body.includes(facebook),`footer Facebook href wrong: ${x.p}`)});
assert(fs.existsSync(path.join(root,'404.html')),'branded 404.html missing');
console.log(`PASS ${preview.length} preview pages; ${menus.length} menu pages; static acceptance checks`);
